# Generated by Django 5.2.12 on 2026-03-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
