# Generated by Django 5.2.12 on 2026-03-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0002_rename_documents_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Versioning',
            new_name='Version',
        ),
    ]
