# Generated by Django 5.2.12 on 2026-03-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0003_rename_versioning_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
