# Generated by Django 5.2.12 on 2026-03-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0004_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted',
            field=models.BooleanField(default=False),
        ),
    ]
