# Generated by Django 5.2.12 on 2026-03-19 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0006_alter_patient_profile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_profile',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profiles', to='trialpilot.document'),
        ),
    ]
