# Generated by Django 5.2.12 on 2026-03-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0007_alter_patient_profile_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='file_path',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
    ]
