# Generated by Django 5.2.12 on 2026-03-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0008_version_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
