# Generated by Django 5.2.12 on 2026-04-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0009_alter_treatment_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('diary', 'Clinical Diary'), ('trial', 'Clinical Trial')], max_length=20),
        ),
        migrations.CreateModel(
            name='Patient_trial_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('eligible', 'Eligible'), ('ineligible', 'Ineligible'), ('inconclusive', 'Inconclusive')], max_length=20)),
                ('deterministic_result', models.BooleanField(default=False)),
                ('llm_justification', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_matches', to='trialpilot.patient_profile')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_matches', to='trialpilot.document')),
            ],
            options={
                'unique_together': {('patient', 'trial')},
            },
        ),
        migrations.CreateModel(
            name='Trial_criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('inclusion', 'Inclusion'), ('exclusion', 'Exclusion')], max_length=20)),
                ('criterion', models.TextField()),
                ('logical_rule', models.JSONField(blank=True, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_criteria', to='trialpilot.document')),
            ],
        ),
        migrations.CreateModel(
            name='Criterion_evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('patient_value', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluation_details', models.JSONField(blank=True, null=True)),
                ('deterministic_justification', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_evaluations', to='trialpilot.patient_trial_match')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='trialpilot.trial_criteria')),
            ],
            options={
                'unique_together': {('match', 'criterion')},
            },
        ),
    ]
