# Generated by Django 5.2.12 on 2026-04-08 10:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0010_alter_document_type_patient_trial_match_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial_criteria',
            old_name='criterion',
            new_name='raw_criterion',
        ),
        migrations.RemoveField(
            model_name='trial_criteria',
            name='logical_rule',
        ),
        migrations.AddField(
            model_name='trial_criteria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial_criteria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trial_criteria',
            name='validated_criterion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Logic_criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_field_name', models.CharField(max_length=100)),
                ('raw_operator', models.CharField(max_length=20)),
                ('raw_logic_json', models.JSONField(blank=True, null=True)),
                ('validated_field_name', models.CharField(max_length=100)),
                ('validated_operator', models.CharField(max_length=20)),
                ('validated_logic_json', models.JSONField(blank=True, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logic', to='trialpilot.trial_criteria')),
            ],
        ),
    ]
