# Generated by Django 5.2.12 on 2026-04-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0011_rename_criterion_trial_criteria_raw_criterion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logic_criteria',
            old_name='raw_logic_json',
            new_name='raw_logic',
        ),
        migrations.RenameField(
            model_name='logic_criteria',
            old_name='validated_logic_json',
            new_name='validated_logic',
        ),
        migrations.RemoveField(
            model_name='logic_criteria',
            name='raw_field_name',
        ),
        migrations.RemoveField(
            model_name='logic_criteria',
            name='raw_operator',
        ),
        migrations.RemoveField(
            model_name='logic_criteria',
            name='validated_field_name',
        ),
        migrations.RemoveField(
            model_name='logic_criteria',
            name='validated_operator',
        ),
    ]
