# Generated by Django 5.2.12 on 2026-04-24 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0012_rename_raw_logic_json_logic_criteria_raw_logic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 24, 13, 37, 36, 348716, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
