# Generated by Django 5.2.12 on 2026-05-04 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0013_patient_profile_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leucocitos', models.FloatField(blank=True, null=True)),
                ('neutrofilos', models.FloatField(blank=True, null=True)),
                ('neutrofilos_percent', models.FloatField(blank=True, null=True)),
                ('linfocitos', models.FloatField(blank=True, null=True)),
                ('linfocitos_percent', models.FloatField(blank=True, null=True)),
                ('monocitos', models.FloatField(blank=True, null=True)),
                ('monocitos_percent', models.FloatField(blank=True, null=True)),
                ('eosinofilos', models.FloatField(blank=True, null=True)),
                ('eosinofilos_percent', models.FloatField(blank=True, null=True)),
                ('basofilos', models.FloatField(blank=True, null=True)),
                ('basofilos_percent', models.FloatField(blank=True, null=True)),
                ('eritrocitos', models.FloatField(blank=True, null=True)),
                ('hemoglobina', models.FloatField(blank=True, null=True)),
                ('hematocrito', models.FloatField(blank=True, null=True)),
                ('vc_medio', models.FloatField(blank=True, null=True)),
                ('hcm', models.FloatField(blank=True, null=True)),
                ('chcm', models.FloatField(blank=True, null=True)),
                ('rdw', models.FloatField(blank=True, null=True)),
                ('plaquetas', models.FloatField(blank=True, null=True)),
                ('vpm', models.FloatField(blank=True, null=True)),
                ('plaquetocrito', models.FloatField(blank=True, null=True)),
                ('pdw', models.FloatField(blank=True, null=True)),
                ('glicose', models.FloatField(blank=True, null=True)),
                ('azoto_ureico', models.FloatField(blank=True, null=True)),
                ('creatinina', models.FloatField(blank=True, null=True)),
                ('sodio', models.FloatField(blank=True, null=True)),
                ('potassio', models.FloatField(blank=True, null=True)),
                ('proteinas_totais', models.FloatField(blank=True, null=True)),
                ('albumina', models.FloatField(blank=True, null=True)),
                ('calcio', models.FloatField(blank=True, null=True)),
                ('osmolalidade', models.FloatField(blank=True, null=True)),
                ('ldh', models.FloatField(blank=True, null=True)),
                ('ast', models.FloatField(blank=True, null=True)),
                ('alt', models.FloatField(blank=True, null=True)),
                ('fosfatase_alcalina', models.FloatField(blank=True, null=True)),
                ('gama_gt', models.FloatField(blank=True, null=True)),
                ('bilirrubina_total', models.FloatField(blank=True, null=True)),
                ('creatina_cinase', models.FloatField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='trialpilot.patient_profile')),
            ],
        ),
    ]
