# Generated by Django 5.2.12 on 2026-05-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0014_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_profile',
            name='pathology_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
