# Generated by Django 5.2.12 on 2026-05-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0015_patient_profile_pathology_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_profile',
            name='pathology_group',
            field=models.CharField(blank=True, choices=[('cabeca_pescoco', 'Cabeça e Pescoço'), ('dermatologia', 'Dermatologia'), ('digestivo', 'Digestivo'), ('ginecologia', 'Ginecologia'), ('mama', 'Mama'), ('oncologia_pediatrica', 'Oncologia Pediátrica'), ('pele', 'Pele'), ('pneumologia', 'Pneumologia'), ('snc', 'Tumores do Sistema Nervoso Central'), ('tne', 'Tumores Neuroendócrinos')], max_length=255, null=True),
        ),
    ]
