# Generated by Django 5.2.12 on 2026-05-06 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0016_alter_patient_profile_pathology_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_name', models.CharField(max_length=255)),
                ('pathology_group', models.CharField(choices=[('cabeca_pescoco', 'Cabeça e Pescoço'), ('dermatologia', 'Dermatologia'), ('digestivo', 'Digestivo'), ('ginecologia', 'Ginecologia'), ('mama', 'Mama'), ('oncologia_pediatrica', 'Oncologia Pediátrica'), ('pele', 'Pele'), ('pneumologia', 'Pneumologia'), ('snc', 'Tumores do Sistema Nervoso Central'), ('tne', 'Tumores Neuroendócrinos')], max_length=50)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recruiting', 'Recruiting'), ('closed', 'Closed'), ('not_yet', 'Not Yet Recruiting'), ('completed', 'Completed')], max_length=20)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_trial', to='trialpilot.document')),
            ],
        ),
    ]
