# Generated by Django 5.2.12 on 2026-05-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0017_clinicaltrial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltrial',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
