# Generated by Django 5.2.12 on 2026-05-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0021_remove_criterion_evaluation_evaluation_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_profile',
            name='gender',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
