# Generated by Django 5.2.12 on 2026-05-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0022_patient_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
