# Generated by Django 5.2.12 on 2026-06-02 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0025_criterion_evaluation_evaluation_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial_cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='trialpilot.clinicaltrial')),
            ],
        ),
        migrations.AddField(
            model_name='trial_criteria',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='trialpilot.trial_cohort'),
        ),
    ]
