# Generated by Django 5.2.12 on 2026-06-24 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialpilot', '0026_trial_cohort_trial_criteria_cohort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial_criteria',
            name='document',
        ),
        migrations.AddField(
            model_name='trial_criteria',
            name='clinical_trial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trial_criteria', to='trialpilot.clinicaltrial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient_trial_match',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_matches', to='trialpilot.clinicaltrial'),
        ),
    ]
