namespace: teses-26
pullsecretname: regcred
replicaCount: 1
image:
  repository: git.ulscoimbra.min-saude.pt/teses26/trialpilot
  tag: v0.0.1
  pullPolicy: IfNotPresent
containerPort: 8000
service:
  type: NodePort
  port: 8000
  targetPort: 8000
env:
  DJANGO_THESES_DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "127.0.0.1,localhost,172.19.2.222"
  TESSERACT_CMD: "tesseract"
  POPPLER_PATH: ""
secretName: trialpilot-secret
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
backend:
  image:
    tag: v0.0.1
frontend:
  image:
    tag: v0.0.1
